config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/contact'
  get 'pages/admin'

  devise_for :users
  resources :users

  resources :request_types, only: [:index]
  resources :notes, only: [:create]

  resources :service_requests do
    resources :notes
    get 'export', on: :collection
  end

  resources :request_types

  root to: 'pages#index'
end

app/controllers/request_types_controller.rb
class RequestTypesController < ApplicationController
  respond_to :json

  def index
    @request_types = RequestType.all
  end

  def new
    @request_type = RequestType.new
  end

  def create
    @request_type = RequestType.new(request_type_params)
    authorize! :create, @request_type, :message => 'Not authorized as an administrator.'
    respond_to do |format|
      if @request_type.save
        flash[:alert] = "Request type ##{@request_type.id} was created!"
        format.html { redirect_to request_types_path }
        format.json { head 201 }
      else
        flash[:alert] = @request_type.errors.full_messages.join('. ')
        format.html { render action: "new" }
        format.json { head 400 }
      end
    end
  end

  def edit
    @request_type = RequestType.find(params[:id])
  end

  def update
    @request_type = RequestType.find(params[:id])
    authorize! :update, @request_type, :message => 'Not authorized as an administrator.'
    respond_to do |format|

      if @request_type.update_attributes(request_type_params)
        format.html { redirect_to request_types_path, alert: 'Request Type was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @request_type = RequestType.find(params[:id])
    authorize! :destroy, @request_type, :message => 'Not authorized as an administrator.'
    @request_type.destroy

    respond_to do |format|
      format.html { redirect_to request_types_url }
    end
  end

  private

  def request_type_params
    params.require(:request_type).permit(
      :category, :request
    )
  end

end

app/views/request_types/_form.html.erb
<div ng-controller="RequestTypesCtlr">
  <h1>Request Type Form</h1>
  <%= simple_form_for @request_type do |f| %>
    <div class="form-group">
      <label class="col-sm-2 control-label">Category</label>
      <div class="col-sm-10">
        <%= f.input :category, label: false  %>
      </div>
    </div>

    <div class="form-group">
      <label class="col-sm-2 control-label">Request</label>
      <div class="col-sm-10">
        <%= f.input :request, label: false  %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      </div>
    </div>
  <% end %>
</div>

app/views/request_types/edit.html.erb
<%= render partial: 'form' %>

app/views/request_types/index.html.erb
<div ng-controller="RequestTypesCtlr">
  <h1>Request Types</h1>
  <div>
    <input type="text" id="query" ng-model="query" placeholder="Search" class="search-input"/>
     <p><%= link_to "Create New Request Type", new_request_type_path, class: "btn btn-default" %></p>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Category</th>
          <th>Request</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>

      <tr ng-repeat="request_type in request_types | filter:query" class="list-item" >
        <td class="col-md-2">{{request_type.category }}</td>
        <td>{{request_type.request }}</td>
        <td><a href="/request_types/{{request_type.id}}/edit">Edit</a></td>
      </tr>
      <tbody>
    </table>
  </div>
</div>

app/views/request_types/new.html.erb
<%= render partial: 'form' %>