config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/contact'
  get 'pages/admin'

  devise_for :users
  resources :users

  resources :request_types, only: [:index]
  resources :notes, only: [:create]

  resources :service_requests do
    resources :notes
    get 'export', on: :collection
  end

  resources :request_types

  root to: 'pages#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w(admin staff)
  validates :role,
    presence: true,
    inclusion: { in: ROLES }

  has_many :created, class_name: "ServiceRequest", inverse_of: :creator

  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable

  # Upon creation, users must immediately reset their passwords when first
  # logging in
  before_create :set_password_as_expired

  # Updating the password resets `password_updated_at`
  before_save :touch_password_updated_at, :if => ->{ password.present? }

  PASSWORD_EXPIRATION_TIME = 90.days
  def password_expired?
    (password_updated_at + PASSWORD_EXPIRATION_TIME).past?
  end

  def active_for_authentication?
    super && !disabled
  end

  def admin?
    role == "admin"
  end

  def staff?
    role == "staff"
  end

  private
  def set_password_as_expired
    self.password_updated_at = Time.at(0) unless password_updated_at.present?
  end

  def touch_password_updated_at
    self.password_updated_at = Time.now
  end
  

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_filter :authenticate_scope!, :only => [:new, :create]


#  def check_permissions
#    authorize! :create, resource
#  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]
  skip_before_filter :check_for_expired_password, only: [:show, :edit, :update]

  def index
    authorize! :manage, User
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
    authorize! :update, @user
  end

  def create
    authorize! :create, User

    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:alert] = "Request ##{@user.id} was created!"
        format.html { redirect_to users_path }
      else
        flash[:alert] = @user.errors.full_messages.join('. ')
        format.html { render action: "new" }
      end
    end
  end

  def update
    authorize! :update, @user

    respond_to do |format|
      if @user.update!(user_params)
        format.html {
          if @user == current_user
            sign_in @user, bypass: true
            redirect_to root_url, alert: 'Your profile was successfully updated.'
          else
            redirect_to users_url, alert: 'User was successfully updated.'
          end
        }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    authorize! :destroy, @user

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end

  private
    def set_user
      if params[:id] == 'current'
        @user = current_user
      else
        @user = User.find(params[:id])
      end
    end

    def user_params
      allowed_params = [:email, :name, :phone, :password]
      allowed_params << [:role, :disabled] if can? :manage, User

      user_params = params.require(:user).permit(*allowed_params)
      user_params.delete(:password) if user_params[:password].blank?
      user_params
    end
end

app/views/users/_form.html.slim
= simple_form_for @user, wrapper: :horizontal_form, html: { class: 'form-horizontal' } do |f|
  = f.input :name, label: "Name"
  = f.input :email, label: "Email"
  = f.input :phone, label: "Phone"
  = f.input :password, label: "Password", placeholder: "if left empty, password will remain unchanged"
  = f.input :role, label: "Role", prompt: false, collection: User::ROLES, label_method: :humanize
  = f.input :disabled, label: "Disabled?"

  = f.button :submit, value: "Submit"

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>

app/views/users/index.html.slim
= link_to "New User", new_user_path, class: "btn btn-success"

table.table.table-hover
  thead
    tr
      th Name
      th Email
      th Phone
      th Role
      th Actions
  tbody
    - @users.each do |user|
      tr
        td= user.name
        td= mail_to(user.email)
        td= user.phone
        td= user.role
        td
          = link_to "Edit", edit_user_path(user)

app/views/users/new.html.erb
<h1>Add New User</h1>
<%= render partial: 'form' %>