config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/contact'
  get 'pages/admin'

  devise_for :users
  resources :users

  resources :request_types, only: [:index]
  resources :notes, only: [:create]

  resources :service_requests do
    resources :notes
    get 'export', on: :collection
  end

  resources :request_types

  root to: 'pages#index'
end

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/admin.html.erb
        <div class="container">
          <div class="well" align="center">
            <p class="lead">From this page, you can Create and Manage Users and Export Data.</p>
          </div>
        </div>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <%= link_to image_tag("Users.png", class: "img-square", width: '120px', height: '120px'), users_path %>
          <h2>Manage Users</h2>
          <p>Edit user profiles, activate or deactivate users, or promote users.</p>
          <p><%= link_to "Manage Users", users_path, class: "btn btn-default" %></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
          <%= link_to image_tag("ToolBox.png", class: "img-square", width: '120px', height: '120px'), request_types_path %>
          <h2>Manage Request Types</h2>
          <p>Define a new work request type. Manage categories of requests.</p>
          <p><%= link_to "Request Types", request_types_path, class: "btn btn-default" %></p>
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-4">
          <%= image_tag("VistalCO/Download.png", class: "img-square", width: '140px', height: '140px') %>
          <h2>Export Data</h2>
          <p>Export and download your data in CSV format, so you can import it into Access or other tools.</p>
          <a class="btn btn-default" href="/service_requests/export" role="button">Export All Data</a>
          <p><div id='export_range' class="btn btn-default">Export Date Range</div></p>
        </div><!-- /.col-lg-4 -->


<div id="export_modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Export Data</h4>
      </div>
      <div clas='container'>
        <form>
          <div>
            <div class='col-md-2 col-md-offset-3'>
              <label>Start Date</label>
            </div>
            <div class='col-md-7'>
              <input id='start_date' required type='date'>
            </div>
          </div>
          <div class='margin-10'>
            <div class='col-md-2 col-md-offset-3'>
              <label>End Date</label>
            </div>
            <div class='col-md-7'>
              <input id='end_date' required type='date'>
            </div>
          </div>
          <div style="margin:10px;text-align:center">
            <input type='submit' id='export_range_submit' class="btn btn-default" value='Export'>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  $('#export_range').click(function(){
    $('#export_modal').modal('show');
  });

  $('#export_range_submit').click(function(){
    event.prevent_default

    var start_date = $('#start_date').val();
    var end_date = $('#end_date').val();
    if( start_date !== '' && end_date !== ''){
      $('#export_modal').modal('hide');
      window.location.replace("/service_requests/export?start_date="+start_date+"&end_date="+end_date);
    }
  });
</script>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/index.html.erb
  

  <!-- Carousel
    ================================================== -->
        <div class="container">
          <div class="jumbotron">
            <p><%= image_tag("color_logo.png", width: '150px', height: '150px', style: 'float: left; padding: 0px 20px 0px 0px;') %>Pathway Homes provides housing and support services for adults with severe and persistent mental illness. This application, developed at <a href="http://rubyforgood.com/">Ruby for Good</a>, helps Pathway Homes manage maintenance requests for the properties they oversee.</p>
            <% if user_signed_in? %>
             <p>&nbsp;</p>
            <% else %>
              <p align="center"><%= link_to "Login", new_user_session_path, class: "btn btn-lg btn-primary" %></p>
            <% end %>
          </div>
        </div>

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <%= link_to image_tag("VistalCO/Config-Tools.png", class: "img-square", width: '140px', height: '140px'),  new_service_request_path %>
          <h2>Need Service?</h2>
          <p>Does one of our properties need attention? Open a request and we'll get someone right on it</p>
          <p><%= link_to "Create New Request", new_service_request_path, class: "btn btn-default" %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= link_to image_tag("review_request.png", class: "img-square", width: '140px', height: '140px'), service_requests_path %>
          <h2>Review Requests</h2>
          <p>Review your open requests and see what others are reporting in.</p>
          <p><%= link_to "View Requests", service_requests_path, class: "btn btn-default" %></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <%= link_to image_tag("VistalCO/Docs.png", class: "img-square", width: '140px', height: '140px'), "http://www.pathwayhomes.org/employee-home" %>
          <h2>Additional Materials</h2>
          <p>Visit the Employee page for additional supporting forms and other documentation.</p>
          <p><a class="btn btn-default" href="http://www.pathwayhomes.org/employee-home" role="button">Employee Page &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->