config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'
  get 'pages/contact'
  get 'pages/admin'

  devise_for :users
  resources :users

  resources :request_types, only: [:index]
  resources :notes, only: [:create]

  resources :service_requests do
    resources :notes
    get 'export', on: :collection
  end

  resources :request_types

  root to: 'pages#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PathwayHomes</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>

<body ng-app="pathwayHomes" data-current-user-id="<%= current_user && current_user.id %>">
  <div class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Maintenance Request Tracker</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "New Request", new_service_request_path %></li>
          <li><%= link_to "View Requests", service_requests_path %></a></li>
          <% if user_signed_in? && current_user.admin? %>
            <li><a href="/pages/admin">Admin</a></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li><a href="#">Logged in as <strong><%= current_user.name %></strong></a></li>
                <li><%= link_to 'Edit profile', edit_user_path(current_user.id) %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Login", new_user_session_path %></li>
              <% end %>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

  <div class="container" ng-controller="MainCtlr">
    <div class="col-sm-8 alert" data-alert="<%= alert %>" ng-class="notice.type" role="alert" ng-show="notice.message">{{notice.message}}</div>

    <%= yield %>
  </div>
</body>
</html>